import Carousel from './components/carousel/Carousel'
import Navbar from './components/nav/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'WebSite',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Carousel />
        <div className="pb-2 pt-2">
          {children}
        </div>
      </body>
    </html>
  )
}
